POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "username" : "Juiced",
    "email" : "juiced30@gmail.com",
    "password" : "jmlesfrites"
}

###

POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email" : "juiced30@gmail.com",
    "password" : "jmlesfrites"
}

###

GET http://localhost:5000/user/me
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjEzNzE1Mzc1NmMyMGFkYmI2OGM1YjZjIn0sImlhdCI6MTYzMTAwNjI4NCwiZXhwIjoxNjMxMDA5ODg0fQ.rekZTJvqI4d8zl5swHRbN3XriuyG50ai0QG-CPdLJRM
